# Config about experiments and output for the various models

[predator_prey]
GENERATE_REPORTS = false
GENERATE_PLOTS = false
VISUALIZE_CHROMOSOMES = false
GENERATE_SUMMARY_CSV = false
GENERATE_MODEL_PLOT = true
MODEL_PLOT_SEPARATE_IMAGES = true
SAVE_FULL_CSV = false
REPORT_VERBOSITY_LEVEL = 2
PLOT_VERBOSITY_LEVEL = 2
CHROMOSOME_VISUALIZATION_TECHNIQUES = ["heatmap", "t-sne", "umap", "pca"]
PLOTS_TO_GENERATE = ["benchmark", "fitness", "species"]

[toxin]
GENERATE_REPORTS = false
GENERATE_PLOTS = false
VISUALIZE_CHROMOSOMES = false
GENERATE_SUMMARY_CSV = false
GENERATE_MODEL_PLOT = true
MODEL_PLOT_SEPARATE_IMAGES = true
SAVE_FULL_CSV = false
REPORT_VERBOSITY_LEVEL = 2
PLOT_VERBOSITY_LEVEL = 2
CHROMOSOME_VISUALIZATION_TECHNIQUES = ["t-sne", "umap"]
PLOTS_TO_GENERATE = ["fitness", "species"]


[function_optimization]
GENERATE_REPORTS = false
GENERATE_PLOTS = false
VISUALIZE_CHROMOSOMES = false
GENERATE_SUMMARY_CSV = false
GENERATE_MODEL_PLOT = true
MODEL_PLOT_SEPARATE_IMAGES = true
SAVE_FULL_CSV = false
REPORT_VERBOSITY_LEVEL = 2
PLOT_VERBOSITY_LEVEL = 2
CHROMOSOME_VISUALIZATION_TECHNIQUES = ["t-sne", "umap"]
PLOTS_TO_GENERATE = ["fitness", "species"]
